### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by semaahmed** [Ruqyai/Ruqia-Library#1]
Code:
df['cleanedtext']= ruqiya.clean_text(df['text'])
df['cleanedtext'].head()

Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_27/3413012263.py in <module>
----> 1 df['cleanedtext']= ruqiya.clean_text(df['text'])
      2 df['cleanedtext'].head()

/opt/conda/lib/python3.7/site-packages/ruqiya/ruqiya.py in clean_text(text)
     44         10-remove_emojis
     45     """
---> 46     text=remove_emails(text)
     47     text=remove_URLs(text)
     48     text=remove_mentions(text)

/opt/conda/lib/python3.7/site-packages/ruqiya/ruqiya.py in remove_emails(text)
    141 def remove_emails(text):
    142     """ remove the `emails` from the `text` ."""
--> 143     text = re.sub(r'[\w\.-]+@[\w\.-]+',"",text)
    144     return text
    145 

/opt/conda/lib/python3.7/re.py in sub(pattern, repl, string, count, flags)
    192     a callable, it's passed the Match object and must return
    193     a replacement string to be used."""
--> 194     return _compile(pattern, flags).sub(repl, string, count)
    195 
    196 def subn(pattern, repl, string, count=0, flags=0):

TypeError: expected string or bytes-like object

I want to solve this problem to use your library.

**Comment by Ruqyai** [comment]
**Try:**

```

from ruqiya.ruqiya import clean_text

df['text']=df['text'].apply(str)
df['cleanedtext']=df['text'].apply(clean_text)
df['cleanedtext'].head()

```

**Comment by Ruqyai** [comment]
**The solution have been added to the documentation as an example**
Look here:
https://github.com/Ruqyai/Ara-NLP-lib#example-2-apply-a-function-to-pandas-dataframe-single-column
